name: buddy

description: A fun desktop companion app

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.12.0 #this is a constraint, when someone tries to run the wrong version, it will throw an error.



dependencies:
  flutter:
    sdk: flutter

  # Allows controlling desktop windows, the one that controls the view window
  window_manager: ^0.3.9

  # Helps manage app state between widgets/windows
  provider: ^6.1.2

  # Allows saving settings/files
  path_provider: ^2.1.4


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:
  # Enables Flutter's Material icons
  uses-material-design: true

  # Your buddy images, gifs, animations
  assets:
    - assets/Gif/
    - assets/PNGs/
    - assets/icon/
  fonts:
    - family: WorkSans
      fonts:
        - asset: assets/Font/WorkSans-Regular.ttf
        - asset: assets/Font/WorkSans-Bold.ttf
          weight: 700